name: 'Deploy the site to an S3 bucket'
description: "Deploy the site to an S3 bucket"
inputs:
  bucket:
    description: 'The bucket Name'
    required: true
  bucket-region:
      description: 'The bucket region'
      required: false
      default: 'us-east-1

dist-folder:
    description: 'The folder to deploy'
    required: true
    default: 'dist'
outputs:
  website-url:
    description: 'The Live link of the website'

runs:
  using: 'node16'
  main: 'main.js'
